# 2D point-mass navigation to a hidden goal (horizon 20), no reset between episodes.
env_name: navigation-nonepisodic
dataset_size: 10000
n_envs: 1000
batch_size: 64
num_epochs: 100
eval_episodes: 40
dagger_steps: 5
n_episodes: 5
